spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://localhost:5432/testjmu
    username: jmuribe
    password: jmuribeX
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true

server:
  tomcat:
    use-relative-redirects: true
